<a href="https://colab.research.google.com/github/jugginmysleep/pytorchlearning2/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.view(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(-1,3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [13]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.reshape(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3[1] = 102938
my_torch3

tensor([     0, 102938,      2,      3,      4,      5,      6,      7,      8,
             9])

In [15]:
my_torch4


tensor([[     0, 102938,      2,      3,      4],
        [     5,      6,      7,      8,      9]])

In [16]:
my_torch5 = torch.arange(10)
my_torch5[7]

tensor(7)

In [17]:
my_torch5[1:4]

tensor([1, 2, 3])

In [19]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [20]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [27]:
my_torch6[0:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])